"""create initial database tables

Revision ID: fd57f184e2b9
Revises: 
Create Date: 2026-05-28 01:29:57.008802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd57f184e2b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('rsa_public_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockchain_dataset_id', sa.Integer(), nullable=True),
    sa.Column('owner_wallet_address', sa.String(length=42), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ipfs_cid', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=255), nullable=True),
    sa.Column('encrypted_aes_key_for_owner', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_format', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_wallet_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_blockchain_dataset_id'), 'datasets', ['blockchain_dataset_id'], unique=True)
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_index(op.f('ix_datasets_owner_wallet_address'), 'datasets', ['owner_wallet_address'], unique=False)
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['wallet_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_dataset_id'), 'access_logs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_access_logs_wallet_address'), 'access_logs', ['wallet_address'], unique=False)
    op.create_table('dataset_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('recipient_wallet_address', sa.String(length=42), nullable=False),
    sa.Column('encrypted_aes_key_for_recipient', sa.Text(), nullable=True),
    sa.Column('access_status', sa.String(length=30), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['recipient_wallet_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'recipient_wallet_address', name='uq_dataset_recipient_access')
    )
    op.create_index(op.f('ix_dataset_access_dataset_id'), 'dataset_access', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_access_id'), 'dataset_access', ['id'], unique=False)
    op.create_index(op.f('ix_dataset_access_recipient_wallet_address'), 'dataset_access', ['recipient_wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_access_recipient_wallet_address'), table_name='dataset_access')
    op.drop_index(op.f('ix_dataset_access_id'), table_name='dataset_access')
    op.drop_index(op.f('ix_dataset_access_dataset_id'), table_name='dataset_access')
    op.drop_table('dataset_access')
    op.drop_index(op.f('ix_access_logs_wallet_address'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_dataset_id'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index(op.f('ix_datasets_owner_wallet_address'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_blockchain_dataset_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
